config:
  # Replace (if needed) IP address of VM [node]
  target: http://scapp_products-daemon
  phases:
    - duration: 30
      arrivalRate: 200
scenarios:
  - flow:
    - get:
        url: /products
